### ISSUE TITLE
Issues when making new posts

### ISSUE THREAD

**Issue by kawaii** [kawaiiforums/mybb-adrem#3]
When making a new post via the full reply dialogue the user will recieve the following error message;
```
Fatal error: Uncaught Error: Class 'adrem\ContentEntity\Post' not found in /var/www/html/inc/plugins/adrem/hooks_frontend.php:269 Stack trace: #0 /var/www/html/inc/class_plugins.php(142): adrem\Hooks\datahandler_post_insert_post_end(Object(PostDataHandler)) #1 /var/www/html/inc/datahandlers/post.php(1333): pluginSystem->run_hooks(Array, Object(PostDataHandler)) #2 /var/www/html/newreply.php(473): PostDataHandler->insert_post() #3 {main} thrown in /var/www/html/inc/plugins/adrem/hooks_frontend.php on line 269
```
When posts are made via the quick reply it causes the AJAX to break and the user is greeted with the ubiquitous 'spinner' until they refresh the page - where there post will finally display. No logs are found in the Mod CP Inspection Logs after this however, so I suspect it bypasses the moderation entirely.

**Comment by kawaii** [comment]
The following is also observed when making a new thread too;
```
Fatal error: Uncaught Error: Class 'adrem\ContentEntity\Post' not found in /var/www/html/inc/plugins/adrem/hooks_frontend.php:253 Stack trace: #0 /var/www/html/inc/class_plugins.php(142): adrem\Hooks\datahandler_post_insert_thread_end(Object(PostDataHandler)) #1 /var/www/html/inc/datahandlers/post.php(1798): pluginSystem->run_hooks(Array, Object(PostDataHandler)) #2 /var/www/html/newthread.php(405): PostDataHandler->insert_thread() #3 {main} thrown in /var/www/html/inc/plugins/adrem/hooks_frontend.php on line 253```
